function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
	msg.post("@render:", "use_fixed_projection", { zoom = 4 })

	-- Crear un goblin
    local goblin_instances = collectionfactory.create("/enemies#enemy_factory", vmath.vector3(100, 100, 0))
	-- Obtener la URL del Game Object principal
	local goblin_url = goblin_instances[hash("/enemy")]
    msg.post(goblin_url, "set_enemy_type", { type = "goblin" })

    -- Crear un dwarf
    local dwarf_instances = collectionfactory.create("/enemies#enemy_factory", vmath.vector3(200, 200, 0))
    local dwarf_url = dwarf_instances[hash("/enemy")]
    msg.post(dwarf_url, "set_enemy_type", { type = "dwarf" })
	
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
