
local function_registry = require "main.function_registry"

local Combat = require "main/objects/player/Combat"


function init(self)
	-- Add initialization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
    self.player_id = tostring(go.get_id("Player")) -- ID del padre (Player)

    -- Registra la función personalizada
    function_registry.register(self.player_id, "attack", barbarian_attack)
	-- Set properties
	set_properties(self)
end



function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function custom_update(self, dt, properties)
	
end

function fixed_update(self, dt)
	-- This function is called if 'Fixed Update Frequency' is enabled in the Engine section of game.project
	-- Can be coupled with fixed updates of the physics simulation if 'Use Fixed Timestep' is enabled in
	-- Physics section of game.project
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
	if message_id == hash("update") then
		self.attacking = message.attacking
		print("Attacking: " .. tostring(self.attacking))
		local properties = {
			attack_cooldown = message.attack_cooldown,
			attacking = message.attacking,
			last_attack_time = message.last_attack_time
		}
        custom_update(self, message.dt, properties)
    end

	if message_id == hash("init_player_vars") then
        -- Accede al padre (Player) y sobrescribe las variables
        local parent = go.get_id("Player")
        msg.post(parent, "set_player_vars", { 
			max_health = self.max_health, 
			max_energy = self.max_energy, 
			attack_power = self.attack_power, 
			attack_range = self.attack_range,
			attack_speed = self.attack_speed,
			attack_cooldown = self.attack_cooldown
		})
    end

	--check collision
    if message_id == hash("contact_point_response") then
		local parent = go.get_id("Player")
		if message.group == hash("enemy") then
			print("Colisionaste con un enemigo!")
			--[[ if not self.invulnerable then
				self.health = self.health - 10
				print("Salud restante: " .. self.health)
			end ]]
			
			-- Calcular dirección de empuje
			local player_pos = go.get_position() -- Posición del jugador

			local enemy_pos = message.position -- Posición del enemigo (de la colisión)
			local push_direction = vmath.normalize(enemy_pos - player_pos) -- Dirección hacia atrás
			
			-- Enviar mensaje al enemigo con la dirección y fuerza del empuje
			msg.post(message.other_id, "apply_push", { direction = push_direction, force = 200 })
		end
    end

end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end

function set_properties(self)
    self.max_health = 100           -- Salud máxima del jugador
    self.max_energy = 50            -- Energía máxima
    
    -- Atributos de combate
    self.attack_power = 10          -- Poder de ataque (daño que inflige)
    self.attack_speed = 1           -- Velocidad de ataque (segundos entre ataques)
    self.attack_range = 30          -- Rango de ataque (distancia máxima)
    self.attack_cooldown = 1        -- Tiempo de recuperación tras atacar (en segundos)
	self.attacking = false          -- Estado de ataque (verdadero si se encuentra atacando)
   
end

function barbarian_attack(self)
	local properties = {
		attack_cooldown = self.attack_cooldown,
		attacking = self.attacking,
		last_attack_time = self.last_attack_time
	}
	-- Call Attack animation
	Combat.attack(self, properties)
end
