-- NewPlayer.script
local Barbarian = require "main/objects/player/Barbarian"
-- Script modular para manejar al jugador
local Animation = require "main/objects/player/Animation"
local Movement = require "main/objects/player/Movement"
local Combat = require "main/objects/player/Combat"
local StateMachine = require "main.state_machine"

function init(self)
	msg.post(".", "acquire_input_focus")
    -- Variable que contendra al jugador principal
	self.player = nil
	-- Inicializar atributos básicos
	self.health = 100
	self.max_health = 100
	self.energy = 50
	self.max_energy = 50
	self.base_speed = 1000
	self.moving = false
	self.attack_power = 10
	self.attack_cooldown = 0.7
	self.last_attack_time = 0
	self.attacking = false
	self.input = vmath.vector3(0, 0, 0)
	self.dir = vmath.vector3(0, 0, 0)
	self.player_face_dir = vmath.vector3(1, 0, 0) -- Inicialmente mirando a la derecha
	self.push_force = vmath.vector3(0, 0, 0) -- Fuerza de empuje inicial
    self.is_pushed = false -- Bandera para saber si está siendo empujado
	self.input_queue = {}
	self.inputs_released = { left = true, right = true, up = true, down = true } -- check if input is released
	self.attack_collisions = {
		upleft = "#attackcollisionupleft",
		upright = "#attackcollisionupright",
		downleft = "#attackcollisiondownleft",
		downright = "#attackcollisiondownright",
	}
	self.collision_direction = self.attack_collisions.left
	self.move_keys = {
		[hash("up")] = true,
		[hash("down")] = true,
		[hash("left")] = true,
		[hash("right")] = true
	}
	self.attack_keys = {
		[hash("attack_left")] = true,
		[hash("attack_right")] = true,
		[hash("attack_up")] = true,
		[hash("attack_down")] = true
	}

	-- Inicializar máquina de estados
	self.state_machine = StateMachine.new()
	init_state_machine(self)
	-- Desactivar todas las colisiones de ataques usando sus nombres en array
	for _, collision in pairs(self.attack_collisions) do
		msg.post(collision, "disable")
	end
	
	self.cursor = go.get("#sprite", "cursor")
end

function update(self, dt)
	self.state_machine:update(dt)
	
end

function on_message(self, message_id, message, sender)
	if message_id == hash("set_player_type") then
		if message.type == "barbarian" then
			self.player = Barbarian:new()
			self.url = message.url
			self.player_url = message.player_url
			self.max_health = self.player.health
			self.health = self.player.health
			self.base_speed = self.player.speed
			print(self.player.name .. " spawned with " .. self.player.health .. " health.")
		end
	end
	-- Recibir daño
	if message_id == hash("take_damage") then
		self.player:take_damage(message.amount)
		if self.health <= 0 then
			print("Player muerto")
			msg.post("#", "player_die")
			self:die()
		end
	end

	--check collision
    if message_id == hash("contact_point_response") then
		if message.group == hash("enemy") then
			print("Colisionaste con un enemigo!".. message.other_group .. " " .. message.own_group .. " " .. sender)
			--[[ if not self.invulnerable then
				self.health = self.health - 10
				print("Salud restante: " .. self.health)
			end ]]
			if message.own_group == hash("player_weapon") then
				-- Enviar dano al enemigo 
				print("Sender ID: ", message.other_id)
				print("Enemigo atacado ---------------------")
				msg.post(message.other_id, "take_damage", { amount = self.player.attack_damage })
			end
			if message.own_group == hash("player_body") then
				-- Calcular dirección de empuje
				local player_pos = go.get_position() -- Posición del jugador

				local enemy_pos = message.position -- Posición del enemigo (de la colisión)
				local player_push_direction = vmath.normalize(player_pos - enemy_pos)			
				-- Aplica la fuerza de empuje
				self.push_force = player_push_direction * 300 -- Ajusta la magnitud del empuje
				-- Cambia al estado pushed
				self.state_machine:set_state("pushed")	
			end
					
		end
    end
end

function on_input(self, action_id, action)
	-- Agregar a la cola de inputs
	table.insert(self.input_queue, { action_id = action_id, action = action })

	-- Si está atacando, ignorar otros inputs
	if self.state_machine:get_state() == "attacking" then return end

	-- Manejar inputs de movimiento
	if self.move_keys[action_id] then
		if action.pressed then
			self.state_machine:set_state("walking")
		elseif action.released then
			self.state_machine:set_state("idle")
		end
	end

	-- Manejar inputs de ataque
	if action_id == hash("attack") and action.pressed then
		-- Obtener estado actual
		local current_state = self.state_machine:get_state()
		if current_state ~= "attacking" then
			self.state_machine:set_state("attacking")
		end
	end
end

function calculate_player_push_direction(self)
	local player_pos = go.get_position()
	local push_direction = vmath.normalize(self.input)
	return push_direction
end

function init_state_machine(self)
	-- Estado "idle"
	-- Estado "idle"
	self.state_machine:add_state("idle", {
		enter = function()
			print("idle enter")
			-- Checar si player mira a la izquierda o derecha
			if self.player_face_dir.x > 0 then
				Animation.play_animation(self, "idle")
			else
				Animation.play_animation(self, "idle_left")
			end
			
		end,
		update = function(dt)
			for key, released in pairs(self.inputs_released) do
				if not released then
					self.state_machine:set_state("walking")
					return
				end
			end
		end,
		exit = function()
			print("idle exit")
		end
	})

	-- Estado "walking"
	self.state_machine:add_state("walking", {
		enter = function()
			print("walking enter")
			if self.player_face_dir.x > 0 then
				Animation.play_animation(self, "walk_down_right")
			else
				Animation.play_animation(self, "walk_down_left")
			end
			if next(self.input_queue) then
				local filtered_queue = {}
				for _, input in ipairs(self.input_queue) do
					if input.action_id ~= hash("attack") then
						table.insert(filtered_queue, input)
					end
				end
				self.input_queue = filtered_queue
			
				-- Procesar los inputs restantes
				for _, input in ipairs(self.input_queue) do
					Movement.handle_input(self, input.action_id, input.action, Animation)
				end
			
				-- Limpiar la cola después de procesar
				self.input_queue = {}
			end
		end,
		update = function(dt)
			print("update walking")
			Movement.move(self, dt)
			local size_vector = vmath.length(self.input)
			-- Checar si no se mueve
			if size_vector == 0 then
				self.state_machine:set_state("idle")
			end
			-- Sino pues procesar los inputs
			if next(self.input_queue) then
				for _, input in ipairs(self.input_queue) do
					Movement.handle_input(self, input.action_id, input.action, Animation)
				end
				self.input_queue = {}
			else
				print("no input super idle")
				self.state_machine:set_state("idle")
			end
		end,
		exit = function()
			print("walking exit")
		end
	})

	-- Estado "attacking"
	self.state_machine:add_state("attacking", {
		enter = function()
			print("attacking enter")
			--self.input_queue = {}
			self.collision_active = false
			-- Si hay movimiento, cambiar la dirección y la animación
            local size_vector = vmath.length(self.input)
            if size_vector > 0 then
                self.dir = vmath.normalize(self.input) -- Normalizamos el vector de dirección
    
                -- Determinar si el personaje mira a la izquierda o derecha
                if self.dir.x > 0 then
                    --go.set_rotation(vmath.quat(), "#sprite") -- Orientación normal (mirando a la derecha)
                    self.player_face_dir.x = 1
                elseif self.dir.x < 0 then
                    --go.set_rotation(vmath.quat_rotation_y(math.pi), "#sprite") -- Reflejar horizontalmente (mirando a la izquierda)
                    self.player_face_dir.x = -1
                end
				print("Con movimiento", self.collision_direction)
                -- Cambiar animación de ataque según direccion vertical
                if self.dir.y > 0 and self.player_face_dir.x > 0 then
					self.collision_direction = self.attack_collisions.upright
                    Animation.play_animation(self, "attack_up_right")
                elseif self.dir.y < 0 and self.player_face_dir.x > 0 then
					self.collision_direction = self.attack_collisions.downright
                    Animation.play_animation(self, "attack_down_right")
				elseif self.dir.y > 0 and self.player_face_dir.x < 0 then
					self.collision_direction = self.attack_collisions.upleft
                    Animation.play_animation(self, "attack_up_left")
                elseif self.dir.y < 0 and self.player_face_dir.x < 0 then
					self.collision_direction = self.attack_collisions.downleft
                    Animation.play_animation(self, "attack_down_left")
				elseif self.dir.x > 0 then
					self.collision_direction = self.attack_collisions.downright
                    Animation.play_animation(self, "attack_down_right")
				elseif self.dir.x < 0 then
					self.collision_direction = self.attack_collisions.downleft
                    Animation.play_animation(self, "attack_down_left")
				end
            else
				print("Sin movimiento", self.collision_direction)
                -- Sin movimiento: usar direccion actual para reflejar el sprite
                if self.player_face_dir.x > 0 then
					self.collision_direction = self.attack_collisions.downright
                    Animation.play_animation(self, "attack_down_right")
                else
					self.collision_direction = self.attack_collisions.downleft
                    Animation.play_animation(self, "attack_down_left")
                end
            end
    
            -- Configurar un temporizador para salir del estado de ataque
            self.attack_timer = self.attack_cooldown
            --msg.post("#attackcollision", "enable") -- Habilitar el collisionobject del ataque
			
		end,
		update = function(dt)
			
			-- Obtén el progreso actual de la animación
			local cursor = go.get("#sprite", "cursor")
			local frame_count = go.get("#sprite", "frame_count")
			if cursor >= 1 then
				--print("Último frame alcanzado")
				
			end
		
			-- Calcula el frame actual
			local current_frame = math.floor(cursor * frame_count) + 1 -- +1 porque los frames son 1-indexados
		
			-- Depura el frame actual
			print("Frame actual:", current_frame)
		
			-- Si el frame coincide con el de ataque, activa la colisión
			if (current_frame == 4 or current_frame == 5) and not self.collision_active then
				msg.post(self.collision_direction, "enable")
				self.collision_active = true
			elseif (current_frame ~= 4 and current_frame ~= 5) and self.collision_active then
				msg.post(self.collision_direction, "disable")
				self.collision_active = false
			end

			self.attack_timer = self.attack_timer - dt
			if self.attack_timer <= 0 then
				msg.post("#sprite", "stop_animation")
				
				Animation.stop_animation(self)
				self.state_machine:exit_current_state()
				self.state_machine:set_state("walking")
			end
		end,
		exit = function()
			print("Exiting attacking state")
			msg.post(self.collision_direction, "disable") -- Deshabilitar el collisionobject del ataque
		end
	})

	-- Estado "pushed"
	self.state_machine:add_state("pushed", {
		enter = function()
			-- Configurar la animación de empuje (opcional)
			--Animation.play_animation(self, "pushed")
			-- Ejemplo de efecto visual
			--msg.post("@render:", "shake", { intensity = 5, duration = 0.2 })
			-- La fuerza de empuje ya debe estar configurada al entrar en este estado
		end,
		update = function(dt)
			-- Mover al jugador según la fuerza de empuje
			local current_position = go.get_position()
			local new_position = current_position + self.push_force * dt
			go.set_position(new_position)

			-- Reducir gradualmente la fuerza de empuje
			self.push_force = self.push_force * 0.9 -- Ajusta el factor de desaceleración
			if vmath.length(self.push_force) < 1 then
				self.state_machine:set_state("idle") -- Volver al estado idle cuando el empuje termine
			end
		end,
		exit = function()
			-- Lógica al salir del estado pushed, si es necesario
			self.push_force = vmath.vector3(0, 0, 0) -- Reiniciar la fuerza de empuje
		end
	})

	-- Estado inicial
	self.state_machine:set_state("idle")
end
