-- player.script
-- agregar caracteristicas al basicas del jugador
go.property("child_class_url", hash("/Mage/Mage"))

local Animation = require "main/objects/player/Animation"
local Movement = require "main/objects/player/Movement"
local Combat = require "main/objects/player/Combat"
local function_registry = require "main.function_registry"
local StateMachine = require "main.state_machine"


function init(self)
    msg.post(".", "acquire_input_focus")
    --Init function_registry
    self.attack = nil -- Función personalizada
    --child url
    self.class_url = msg.url(self.child_class_url) -- Referencia al script de la clase (Barbarian)
    
    -- Atributos básicos del jugador
    self.health = 100               -- Salud actual del jugador
    self.max_health = 100           -- Salud máxima del jugador
    self.energy = 50                -- Energía o stamina del jugador
    self.max_energy = 50            -- Energía máxima
    
    -- Atributos de combate
    self.attack_power = 10          -- Poder de ataque (daño que inflige)
    self.attack_speed = 1           -- Velocidad de ataque (segundos entre ataques)
    self.attack_range = 30          -- Rango de ataque (distancia máxima)
    self.attack_cooldown = 1        -- Tiempo de recuperación tras atacar (en segundos)
    self.last_attack_time = 0       -- Última vez que atacó, para gestionar el cooldown
    self.attacking = false          -- Estado de ataque (verdadero si se encuentra atacando)
    
    -- Atributos de defensa
    
    -- Atributos de movimiento
    self.base_speed = 100           -- Velocidad base de movimiento
    self.moving = false             -- Estado de movimiento (verdadero si se está moviendo)
    self.player_face_dir = vmath.vector3(0, 0, 0)
    self.input = vmath.vector3(0, 0, 0)  -- Dirección de movimiento
    self.dir = vmath.vector3(0, 0, 0)  -- Dirección del movimiento

    -- Estado y control de daño
    self.invulnerable = false       -- Estado de invulnerabilidad (verdadero si es invulnerable)
    self.damage_cooldown = 1        -- Tiempo de recuperación tras recibir daño (en segundos)
    self.last_damage_time = 0       -- Última vez que recibió daño, para gestionar el cooldown
    
    -- Atributos de juego y progresión
    self.score = 0                  -- Puntuación o experiencia del jugador
    self.state = "idle"             -- Estado del jugador: "idle", "walking", "attacking", etc.
    
    -- Otras variables de animación
    self.current_animation = nil    -- Para rastrear la animación actual y evitar cambios

    
    self.inputs_released = { left = true, right = true, up = true, down = true } -- check if input is released
    self.move_keys = {
        [hash("up")] = true,
        [hash("down")] = true,
        [hash("left")] = true,
        [hash("right")] = true
    }
    --table for 8 attacks 
    self.attack_keys = {
        [hash("attack_left")] = true,
        [hash("attack_right")] = true,
        [hash("attack_up")] = true,
        [hash("attack_down")] = true,
        [hash("attack_up_left")] = true,
        [hash("attack_up_right")] = true,
        [hash("attack_down_left")] = true,
        [hash("attack_down_right")] = true
    }
    self.pressed_keys = {}

    --Init state machine
    init_state_machine(self)
    -- Notifica a los scripts hijos para que puedan sobrescribir
    msg.post(self.class_url, "init_player_vars")
    
end

function update(self, dt)
    self.sm:update(dt)
    -- if not self.attacking then
    --     Movement.move(self, dt)
    --     print("not attacking")
    -- end
    -- if self.attacking then
    --     set_all_movement_properties_to_zero(self)
    --     attack_cooldown(self, dt)
    --     print("attacking")
    -- end
    --Combat.attack_cooldown(self, dt)
    --Combat.damage_cooldown(self, dt)
    -- getting player properties to send to child
    local player_vars = setting_player_vars(self, dt)
    -- Delegar lógica específica de la clase
    --msg.post(self.class_url, "update", player_vars)
    
end

function setting_player_vars(self, dt)
    return { 
        dt = dt,
        attack_cooldown = self.attack_cooldown,
        attacking = self.attacking,
        last_attack_time = self.last_attack_time
    }
end

function on_input(self, action_id, action)
    self.input_queue = self.input_queue or {}
    table.insert(self.input_queue, { action_id = action_id, action = action })
    -- Ignorar entrada si está atacando
    if self.sm:get_state() == "attacking" then
        return
    end
    --detecting if player is attacking
    if action_id == hash("attack") and action.pressed then
        self.sm:set_state("attacking")
    
    end

    if self.sm:get_state() ~= "attacking" then
        for key, value in pairs(self.move_keys) do
            --print(key, value)
        end
        -- Procesar input de movimiento
        --detecting if player is moving
        if self.move_keys[action_id] and action.pressed then
            self.pressed_keys[action_id] = true
            self.sm:set_state("walking")
        elseif self.move_keys[action_id] and action.released then
            print("released")
            self.pressed_keys[action_id] = false
            --self.sm:set_state("idle")
        end
    end
end

function on_message(self, message_id, message, sender)
    --Set child class variables
    if message_id == hash("set_player_vars") then
        for k, v in pairs(message) do
            self[k] = v
        end
    end    
    --print(message_id, tostring(message.id))
    --check if message.id contains attack words
    if message_id == hash("complete_animation") and message.id == hash("attack_right") then
        --self.attacking = false
        print("Ataque completado!")
    end
    --check state_machine 
    if message_id == hash("change_state") then
        print("Changing state to " .. message.id)
        self.sm:set_state(message.id)
    end
    --check collision
    if message_id == hash("contact_point_response") then
        if message_id == hash("contact_point_response") then
            -- Identificar el grupo del objeto con el que se colisionó
            if message.group == hash("enemy") then
                print("Colisionaste con un enemigo!")
                if not self.invulnerable then
                    self.health = self.health - 10
                    print("Salud restante: " .. self.health)
                end
            elseif message.group == hash("walls") then
                print("Colisión con una pared")
            elseif message.group == hash("attack") then
                print("Ataque conectado con el objetivo!")
                msg.post(sender, "take_damage", { damage = self.attack_power })
            end
            -- URL del otro objeto para más control
            print("Objeto colisionado: " .. tostring(message.other_id))
        end
    end
end

function player_attack(self)
    print("player attack")
    Animation.play_animation(self, "attack_right")
end

function attack_cooldown(self, dt)
    local current_time = socket.gettime()
    -- Ejemplo de gestión de estado "attack cooldown"
    if self.attacking and current_time - self.last_attack_time >= self.attack_cooldown then
        self.attacking = false
        self.last_attack_time = current_time
        print("Attack cooldown finished")
    end
end

function set_all_movement_properties_to_zero(self)
    self.moving = false
    self.dir = vmath.vector3(0, 0, 0)
    self.player_face_dir = vmath.vector3(0, 0, 0)
    self.inputs_released = { up = true, down = true, left = true, right = true }
end

function init_state_machine(self)
    --create states
    self.sm = StateMachine.new()

    self.sm:add_state("idle", {
        enter = function()
            --print("current position", go.get_position())

            --print("idle")
            if self.player_face_dir.x > 0 then
                Animation.play_animation(self, "idle")
            else
                Animation.play_animation(self, "idle_left")
            end
            
        end,
        update = function(dt) 
            if self.input_queue then
                self.sm:set_state("walking")
            else
                self.sm:set_state("idle")
            end
        end,
        exit = function()
            print("idle exit")
            
        end
    })

    self.sm:add_state("walking", {
        enter = function()
            print("walking")
            if self.input_queue then
                for _, input in ipairs(self.input_queue) do
                    Movement.handle_input(self, input.action_id, input.action, Animation)
                end
                self.input_queue = {}
            end
        end,
        update = function(dt)
            Movement.move(self, dt)
            if self.input_queue then
                for _, input in ipairs(self.input_queue) do
                    Movement.handle_input(self, input.action_id, input.action, Animation)
                end
                self.input_queue = {}
            end
        end,
        exit = function()
            print("walking exit")
            
        end
    })

    self.sm:add_state("attacking", {
        enter = function()
            print("Entering attacking state")
    
            -- Si hay movimiento, cambiar la dirección y la animación
            local size_vector = vmath.length(self.input)
            if size_vector > 0 then
                self.dir = vmath.normalize(self.input) -- Normalizamos el vector de dirección
    
                -- Determinar si el personaje mira a la izquierda o derecha
                if self.dir.x > 0 then
                    go.set_rotation(vmath.quat(), "#sprite") -- Orientación normal (mirando a la derecha)
                    self.player_face_dir.x = 1
                elseif self.dir.x < 0 then
                    go.set_rotation(vmath.quat_rotation_y(math.pi), "#sprite") -- Reflejar horizontalmente (mirando a la izquierda)
                    self.player_face_dir.x = -1
                end
    
                -- Cambiar animación de ataque según dirección vertical
                if self.dir.y > 0 then
                    Animation.play_animation(self, "attack_up")
                elseif self.dir.y < 0 then
                    Animation.play_animation(self, "attack_down")
                else
                    Animation.play_animation(self, "attack") -- Animación neutral si no hay dirección vertical
                end
            else
                -- Sin movimiento: usar dirección actual para reflejar el sprite
                if self.player_face_dir.x > 0 then
                    go.set_rotation(vmath.quat(), "#sprite")
                else
                    go.set_rotation(vmath.quat_rotation_y(math.pi), "#sprite")
                end
    
                -- Animación neutral de ataque
                Animation.play_animation(self, "attack")
            end
    
            -- Desactivar movimiento mientras ataca
            -- self.base_speed = 0
            print(msg.url("Barbarian#attackcollision")) -- Verifica si es la URL correcta
    
            -- Configurar un temporizador para salir del estado de ataque
            self.attack_timer = 1 -- Duración del ataque en segundos
            msg.post("Barbarian#attackcollision", "enable") -- Habilitar el collisionobject del ataque
        end,
        update = function(dt)
            -- Reducir el tiempo restante en el estado de ataque
            self.attack_timer = self.attack_timer - dt
            if self.attack_timer <= 0 then
                print("Updating attacking state")
                -- Volver a idle o caminar dependiendo de las teclas presionadas
                --Animation.play_animation(self, "idle")
                self.sm:set_state("walking")
            end
        end,
        exit = function()
            print("Exiting attacking state")
            msg.post("Barbarian#attackcollision", "disable") -- Deshabilitar el collisionobject del ataque
        end
    })
    

    self.sm:set_state("idle")
    
end