-- player.script
local input_left = hash("left")
local input_right = hash("right")
local input_up = hash("up")
local input_down = hash("down")

function init(self)
    msg.post(".", "acquire_input_focus")
    self.speed = 100  -- Velocidad de movimiento
    self.input = vmath.vector3(0, 0, 0)  -- Dirección de movimiento
    self.moving = false  -- Estado de movimiento
    self.dir = vmath.vector3(0, 0, 0)  -- Dirección del movimiento
    self.current_animation = nil  -- Almacena la animación actual
    self.inputs_released = { left = true, right = true, up = true, down = true } -- check if input is released
    self.player_face_dir = vmath.vector3(0, 0, 0)
end

function update(self, dt)
    if self.moving then
        local pos = go.get_position()
        pos = pos + self.dir * self.speed * dt  -- Mueve al jugador en la dirección especificada
        go.set_position(pos)
    end
end

function on_input(self, action_id, action)
    -- Controlar direcciones de movimiento
    if action_id == input_left then
        if action.pressed then
			self.input.x = -1
            self.inputs_released.left = false
            self.player_face_dir.x = -1
        end
		if action.released then
			if not self.inputs_released.right then
                self.input.x = 1
            else
                self.input.x = 0
            end
            self.inputs_released.left = true
		end
	elseif action_id == input_right then
		if action.pressed then
			self.input.x = 1
            self.inputs_released.right = false
            self.player_face_dir.x = 1
        end
		if action.released then
			if not self.inputs_released.left then
                self.input.x = -1
            else
                self.input.x = 0
            end
            self.inputs_released.right = true
		end
	elseif action_id == input_up then
        if action.pressed then
            self.input.y = 1
            self.inputs_released.up = false
        end
        if action.released then
            if not self.inputs_released.down then
                self.input.y = -1
            else
                self.input.y = 0
            end
            self.inputs_released.up = true
        end
    elseif action_id == input_down then
        if action.pressed then
            self.input.y = -1
            self.inputs_released.down = false
        end
        if action.released then
            if not self.inputs_released.up then
                self.input.y = 1
            else
                self.input.y = 0
            end
            self.inputs_released.down = true
        end
	end
    -- Si hay movimiento, cambiar la dirección y la animación
    local size_vector = vmath.length(self.input)
    if size_vector > 0 then
        self.moving = true
        self.dir = vmath.normalize(self.input)  -- Normalizamos el vector de dirección

        -- Cambiar la animación de acuerdo con la dirección y checa si va izquierda o derecha
        if self.dir.x > 0 then
            play_animation(self, "walk_right")
        elseif self.dir.x < 0 then
            play_animation(self, "walk_left")
        elseif self.dir.y > 0 and self.player_face_dir.x > 0 then
            play_animation(self, "walk_up_right")
        elseif self.dir.y > 0 and self.player_face_dir.x < 0 then
            play_animation(self, "walk_up_left")
        elseif self.dir.y < 0 and self.player_face_dir.x > 0 then
            play_animation(self, "walk_down_right")
        elseif self.dir.y < 0 and self.player_face_dir.x < 0 then
            play_animation(self, "walk_down_left")
        end
        
    else
        self.moving = false
        -- Si esta viendo a la derecha, poner la animación en idle normal y si esta viendo a la izquierda, poner la animación en idle mirando a la izquierda
        if self.player_face_dir.x > 0 then
            play_animation(self, "idle")
        else
            play_animation(self, "idle_left")
        end
    end
end

function play_animation(self, animation)
    -- Solo cambia la animación si es diferente de la actual
    if self.current_animation ~= animation then
        msg.post("#sprite", "play_animation", { id = hash(animation) })
        self.current_animation = animation
    end
end
