-- player.script
-- agregar caracteristicas al basicas del jugador
go.property("child_class_url", hash("/Mage/Mage"))

local Animation = require "main/objects/player/Animation"
local Movement = require "main/objects/player/Movement"
local Combat = require "main/objects/player/Combat"
local function_registry = require "main.function_registry"


function init(self)
    msg.post(".", "acquire_input_focus")
    --Init function_registry
    self.attack = nil -- Función personalizada
    --child url
    self.class_url = msg.url(self.child_class_url) -- Referencia al script de la clase (Barbarian)
    
    -- Atributos básicos del jugador
    self.health = 100               -- Salud actual del jugador
    self.max_health = 100           -- Salud máxima del jugador
    self.energy = 50                -- Energía o stamina del jugador
    self.max_energy = 50            -- Energía máxima
    
    -- Atributos de combate
    self.attack_power = 10          -- Poder de ataque (daño que inflige)
    self.attack_speed = 1           -- Velocidad de ataque (segundos entre ataques)
    self.attack_range = 30          -- Rango de ataque (distancia máxima)
    self.attack_cooldown = 1        -- Tiempo de recuperación tras atacar (en segundos)
    self.last_attack_time = 0       -- Última vez que atacó, para gestionar el cooldown
    self.attacking = false          -- Estado de ataque (verdadero si se encuentra atacando)
    
    -- Atributos de defensa
    
    -- Atributos de movimiento
    self.base_speed = 100           -- Velocidad base de movimiento
    self.moving = false             -- Estado de movimiento (verdadero si se está moviendo)
    self.player_face_dir = vmath.vector3(0, 0, 0)
    self.input = vmath.vector3(0, 0, 0)  -- Dirección de movimiento
    self.dir = vmath.vector3(0, 0, 0)  -- Dirección del movimiento

    -- Estado y control de daño
    self.invulnerable = false       -- Estado de invulnerabilidad (verdadero si es invulnerable)
    self.damage_cooldown = 1        -- Tiempo de recuperación tras recibir daño (en segundos)
    self.last_damage_time = 0       -- Última vez que recibió daño, para gestionar el cooldown
    
    -- Atributos de juego y progresión
    self.score = 0                  -- Puntuación o experiencia del jugador
    self.state = "idle"             -- Estado del jugador: "idle", "walking", "attacking", etc.
    
    -- Otras variables de animación
    self.current_animation = nil    -- Para rastrear la animación actual y evitar cambios

    
    self.inputs_released = { left = true, right = true, up = true, down = true } -- check if input is released

     -- Notifica a los scripts hijos para que puedan sobrescribir
     msg.post(self.class_url, "init_player_vars")
    
end

function update(self, dt)
    if not self.attacking then
        Movement.move(self, dt)        
    end
    if self.attacking then
        set_all_movement_properties_to_zero(self)
        attack_cooldown(self, dt)
    end
    --Combat.attack_cooldown(self, dt)
    --Combat.damage_cooldown(self, dt)
    -- getting player properties to send to child
    local player_vars = setting_player_vars(self, dt)
    -- Delegar lógica específica de la clase
    --msg.post(self.class_url, "update", player_vars)
    
end

function setting_player_vars(self, dt)
    return { 
        dt = dt,
        attack_cooldown = self.attack_cooldown,
        attacking = self.attacking,
        last_attack_time = self.last_attack_time
    }
end

function on_input(self, action_id, action)
    if self.attacking then
        set_all_movement_properties_to_zero(self)
    end
    if not self.attacking then
        Movement.handle_input(self, action_id, action, Animation)
        --Override attack
        if action_id == hash("attack") and action.pressed then
            print("attack", self.attacking)
            if not self.attacking then
                print("attacking")
                
                self.last_attack_time = socket.gettime()
                player_attack(self) -- Llama a la función para reproducir la animación
                self.attacking = true
            end
        end
    end
    
    
end

function on_message(self, message_id, message, sender)
    --Set child class variables
    if message_id == hash("set_player_vars") then
        for k, v in pairs(message) do
            self[k] = v
        end
    end    
    print(message_id, tostring(message.id))
    --check if message.id contains attack words
    if message_id == hash("complete_animation") and message.id == hash("attack_right") then
        --self.attacking = false
        print("Ataque completado!")
    end
end

function player_attack(self)
    print("player attack")
    Animation.play_animation(self, "attack_right")
end

function attack_cooldown(self, dt)
    local current_time = socket.gettime()
    -- Ejemplo de gestión de estado "attack cooldown"
    if self.attacking and current_time - self.last_attack_time >= self.attack_cooldown then
        self.attacking = false
        self.last_attack_time = current_time
    end
end

function set_all_movement_properties_to_zero(self)
    self.moving = false
    self.dir = vmath.vector3(0, 0, 0)
    self.player_face_dir = vmath.vector3(0, 0, 0)
    self.inputs_released = { up = true, down = true, left = true, right = true }
end